-- Extend jobs table with apply URL, ATS metadata, carousel, and board source
ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS apply_url             TEXT,
  ADD COLUMN IF NOT EXISTS ats_type              TEXT,
  ADD COLUMN IF NOT EXISTS is_active             BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS company_stage         TEXT,
  ADD COLUMN IF NOT EXISTS description_raw       TEXT,
  ADD COLUMN IF NOT EXISTS source_board          TEXT,
  ADD COLUMN IF NOT EXISTS carousel_slide_urls   JSONB;

-- Extend job_seeker_profiles with contact + portfolio fields
ALTER TABLE job_seeker_profiles
  ADD COLUMN IF NOT EXISTS github_url     TEXT,
  ADD COLUMN IF NOT EXISTS portfolio_url  TEXT,
  ADD COLUMN IF NOT EXISTS city           TEXT,
  ADD COLUMN IF NOT EXISTS phone          TEXT;

-- Carousel metadata (one per job, generated by carousel-service)
CREATE TABLE IF NOT EXISTS carousels (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id      UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  theme       TEXT NOT NULL DEFAULT 'dark',
  slide_urls  JSONB NOT NULL DEFAULT '[]',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (job_id)
);

-- Tracks when a candidate opened or submitted an apply URL
CREATE TABLE IF NOT EXISTS application_events (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id                UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  candidate_profile_id  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  application_id        UUID REFERENCES job_applications(id) ON DELETE SET NULL,
  event_type            TEXT NOT NULL CHECK (event_type IN ('opened', 'submitted')),
  ats_type              TEXT,
  apply_url             TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS application_events_candidate_idx
  ON application_events (candidate_profile_id, created_at DESC);

-- Raw ATS field captures per application event
CREATE TABLE IF NOT EXISTS application_fields (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id              UUID NOT NULL REFERENCES application_events(id) ON DELETE CASCADE,
  candidate_profile_id  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  field_label           TEXT NOT NULL,
  field_value           TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Candidate's best-known value per field label (autofill source of truth)
CREATE TABLE IF NOT EXISTS candidate_field_history (
  candidate_profile_id  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  field_label           TEXT NOT NULL,
  field_value           TEXT,
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (candidate_profile_id, field_label)
);

-- RLS
ALTER TABLE carousels              ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_events     ENABLE ROW LEVEL SECURITY;
ALTER TABLE application_fields     ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidate_field_history ENABLE ROW LEVEL SECURITY;

-- Carousels: public read, service-role write (carousel-service uses service key)
CREATE POLICY "carousels_public_read" ON carousels
  FOR SELECT USING (true);

-- Application events: candidate sees own rows
CREATE POLICY "application_events_own" ON application_events
  FOR ALL USING (candidate_profile_id = auth.uid());

-- Application fields: candidate sees own rows
CREATE POLICY "application_fields_own" ON application_fields
  FOR ALL USING (candidate_profile_id = auth.uid());

-- Field history: candidate sees own rows
CREATE POLICY "candidate_field_history_own" ON candidate_field_history
  FOR ALL USING (candidate_profile_id = auth.uid());
